"""Policy-owned runtime for dependency lock and license refresh workflows."""

from __future__ import annotations

import hashlib
import importlib.util
import json
import os
import re
import shutil
import subprocess  # nosec B404
import sys
import tempfile
from dataclasses import dataclass
from pathlib import Path
from typing import Callable, Dict, Iterable, List, Mapping, Sequence, Tuple

from packaging.requirements import InvalidRequirement, Requirement

from devcovenant.builtin.policies.dependency_management import (
    dependency_management,
)
from devcovenant.core.services.metadata import (
    build_metadata_context,
    metadata_value_list,
    resolve_policy_metadata_bundle,
)
from devcovenant.core.services.policy_registry import (
    load_policy_descriptor,
    resolve_script_location,
)

POLICY_ID = "dependency-management"
_PYTHON_LOCK_OPTION_TOKENS = {
    "--cert",
    "--client-cert",
    "--constraint",
    "--extra-index-url",
    "--find-links",
    "--index-url",
    "--no-binary",
    "--no-index",
    "--only-binary",
    "--prefer-binary",
    "--pre",
    "--requirement",
    "--trusted-host",
    "-c",
    "-f",
    "-i",
    "-r",
}


def _normalize_repo_relative_path_token(raw_value: object) -> str:
    """Return one normalized repo-relative path token."""

    return str(raw_value or "").replace("\\", "/").strip()


@dataclass(frozen=True)
class LockFilePieces:
    """Describe the body of a generated requirements.lock snapshot."""

    body: List[str]


@dataclass(frozen=True)
class LockHandlerResult:
    """Outcome from one lockfile refresh strategy."""

    lock_file: str
    changed: bool
    attempted: bool
    message: str


def _compute_file_hash(path: Path) -> str:
    """Return a stable hash digest for a file."""

    return hashlib.sha256(path.read_bytes()).hexdigest()


def _file_hash_or_missing(path: Path) -> str:
    """Return digest string, with placeholder when file is absent."""

    if not path.exists():
        return "__missing__"
    return _compute_file_hash(path)


def _ensure_tool(command_name: str) -> bool:
    """Return True when a command is available on PATH."""

    return shutil.which(command_name) is not None


def _run_command(
    repo_root: Path,
    args: Sequence[str],
    *,
    extra_env: Dict[str, str] | None = None,
) -> None:
    """Run one lockfile command and raise on failure."""

    env = dict(os.environ)
    if extra_env:
        env.update(extra_env)
    # Reviewed tokenized local command execution; shell use stays forbidden.
    subprocess.run(  # nosec B603
        list(args),
        cwd=repo_root,
        check=True,
        text=True,
        capture_output=True,
        env=env,
    )


def _run_and_detect_change(
    repo_root: Path, lock_path: Path, command: Sequence[str]
) -> bool:
    """Run command and return True when target lockfile changed."""

    before = _file_hash_or_missing(lock_path)
    _run_command(repo_root, command)
    after = _file_hash_or_missing(lock_path)
    return before != after


def _normalise_header(lines: Sequence[str]) -> List[str]:
    """Stabilise pip-compile banners across Python versions."""

    return _normalise_header_for_mode(lines, generate_hashes=False)


def _normalise_header_for_mode(
    lines: Sequence[str],
    *,
    generate_hashes: bool,
    output_name: str = "requirements.lock",
    input_name: str = "requirements.in",
) -> List[str]:
    """Stabilise pip-compile banners across Python versions and modes."""

    python_banner = "# This file is autogenerated by pip-compile"
    command_tokens = ["pip-compile", "--allow-unsafe"]
    if generate_hashes:
        command_tokens.append("--generate-hashes")
    command_tokens.extend(
        [
            "--strip-extras",
            f"--output-file={output_name}",
            input_name,
        ]
    )
    target = "#    " + " ".join(command_tokens)
    result = list(lines)
    for index, line in enumerate(result):
        if line.startswith("#    pip-compile "):
            result[index] = target
            break
    for index, line in enumerate(result):
        if line.startswith(
            "# This file is autogenerated by pip-compile with Python"
        ):
            result[index] = python_banner
            break
    return result


def _split_last_updated(lines: Iterable[str]) -> LockFilePieces:
    """Drop optional Last Updated banner from lockfile body."""

    collected = list(lines)
    if collected and collected[0].startswith("# Last Updated:"):
        return LockFilePieces(collected[1:])
    return LockFilePieces(collected)


def _is_python_lock_option_line(raw_line: str) -> bool:
    """Return True for environment-specific pip option directives."""

    stripped = str(raw_line).strip()
    if not stripped or raw_line[:1].isspace():
        return False
    token = stripped.split(maxsplit=1)[0].split("=", 1)[0]
    return token in _PYTHON_LOCK_OPTION_TOKENS


def _strip_python_lock_option_lines(lines: Sequence[str]) -> List[str]:
    """Remove non-semantic pip option lines from lockfile content."""

    return [
        str(raw_line)
        for raw_line in lines
        if not _is_python_lock_option_line(str(raw_line))
    ]


def _normalise_input_reference_comments(
    lines: Sequence[str],
    *,
    input_name: str,
) -> List[str]:
    """Rewrite `# via -r ...` comments to the configured input label."""

    normalized: List[str] = []
    for raw_line in lines:
        raw_text = str(raw_line)
        match = re.match(
            r"^(?P<indent>\s*#\s*)(?:(?P<via>via)\s+)?-r\s+.+$",
            raw_text,
        )
        if match is not None:
            prefix = match.group("indent")
            via = "via " if match.group("via") else ""
            normalized.append(f"{prefix}{via}-r {input_name}")
            continue
        normalized.append(raw_text)
    return normalized


def _normalize_python_lock_semantics(lines: Sequence[str]) -> List[str]:
    """Compare Python lockfiles by resolved pins, not banner formatting."""

    return _normalize_python_lock_semantics_for_mode(
        lines,
        generate_hashes=False,
    )


def _normalize_python_lock_semantics_for_mode(
    lines: Sequence[str],
    *,
    generate_hashes: bool,
) -> List[str]:
    """Compare Python lockfiles by semantic content for one lock mode."""

    normalized: List[str] = []
    for raw_line in _strip_python_lock_option_lines(lines):
        stripped = str(raw_line).strip()
        if not stripped or stripped.startswith("#"):
            continue
        if raw_line[:1].isspace():
            if generate_hashes and stripped.startswith("--hash=sha256:"):
                normalized.append(stripped.rstrip("\\").strip())
            continue
        normalized.append(stripped.rstrip("\\").strip())
    return normalized


def _compile_requirements_lock(
    repo_root: Path,
    requirements_in: Path,
    *,
    generate_hashes: bool = False,
    existing_lock_lines: Sequence[str] | None = None,
    output_name: str = "requirements.lock",
    input_name: str = "requirements.in",
) -> LockFilePieces:
    """Generate normalised requirements.lock content without touching disk."""

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_lock = Path(tmpdir) / output_name
        _run_pip_compile(
            repo_root,
            requirements_in,
            tmp_lock,
            generate_hashes=generate_hashes,
        )
        normalised = _normalise_header_for_mode(
            tmp_lock.read_text().splitlines(),
            generate_hashes=generate_hashes,
            output_name=output_name,
            input_name=input_name,
        )
        cleaned = _normalise_input_reference_comments(
            _strip_python_lock_option_lines(normalised),
            input_name=input_name,
        )
    if generate_hashes:
        return _split_last_updated(cleaned)
    with_direct_conditionals = _preserve_direct_conditional_requirements(
        cleaned,
        requirements_in,
        source_display_name=input_name,
    )
    return _split_last_updated(with_direct_conditionals)


def _preserve_direct_conditional_requirements(
    compiled_lines: Sequence[str],
    requirements_in: Path,
    *,
    source_display_name: str = "requirements.in",
) -> List[str]:
    """Keep direct exact conditional requirements visible in the lock."""

    preserved_requirements = _collect_direct_conditional_requirements(
        requirements_in
    )
    if not preserved_requirements:
        return list(compiled_lines)

    existing_entries = {
        str(raw_line).strip().rstrip("\\").strip()
        for raw_line in compiled_lines
        if str(raw_line).strip()
        and not str(raw_line).lstrip().startswith("#")
        and not str(raw_line)[:1].isspace()
    }
    result = list(compiled_lines)
    for requirement in preserved_requirements:
        pin_line = _format_direct_conditional_requirement(requirement)
        if pin_line in existing_entries:
            continue
        if result and result[-1] != "":
            result.append("")
        result.append(pin_line)
        result.append(f"    # via -r {source_display_name}")
    return result


def _collect_direct_conditional_requirements(
    requirements_in: Path,
) -> List[Requirement]:
    """Return direct exact conditional requirements from requirements.in."""

    collected: List[Requirement] = []
    for raw_line in requirements_in.read_text(encoding="utf-8").splitlines():
        stripped = raw_line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        if _is_python_lock_option_line(raw_line):
            continue
        try:
            requirement = Requirement(stripped)
        except InvalidRequirement:
            continue
        if requirement.marker is None:
            continue
        specifiers = list(requirement.specifier)
        if len(specifiers) != 1 or specifiers[0].operator != "==":
            continue
        collected.append(requirement)
    return collected


def _format_direct_conditional_requirement(requirement: Requirement) -> str:
    """Return canonical text for one direct exact conditional requirement."""

    specifiers = list(requirement.specifier)
    exact = specifiers[0]
    extras = (
        f"[{','.join(sorted(requirement.extras))}]"
        if requirement.extras
        else ""
    )
    return (
        f"{requirement.name}{extras}=={exact.version} ; "
        f"{requirement.marker}"
    )


def _build_hashed_requirement_block(
    requirement_line: str,
    hashes: Sequence[str],
    *,
    source_display_name: str = "requirements.in",
) -> List[str]:
    """Return one pip-compile-style hashed requirement block."""

    unique_hashes = sorted(
        {str(entry).strip() for entry in hashes if str(entry).strip()}
    )
    if not unique_hashes:
        raise RuntimeError(
            f"Missing hashes for locked requirement `{requirement_line}`."
        )
    block = [f"{requirement_line} \\"]
    last_index = len(unique_hashes) - 1
    for index, digest in enumerate(unique_hashes):
        suffix = " \\" if index < last_index else ""
        block.append(f"    --hash=sha256:{digest}{suffix}")
    block.append(f"    # via -r {source_display_name}")
    return block


def _run_pip_compile(
    repo_root: Path,
    requirements_in: Path,
    output_path: Path,
    *,
    generate_hashes: bool = False,
) -> None:
    """Run pip-compile with the repository's canonical options."""

    if importlib.util.find_spec("piptools") is None:
        raise RuntimeError(
            "pip-tools is required for requirements.lock updates."
        )
    with tempfile.TemporaryDirectory() as cache_dir:
        _run_command(
            repo_root,
            (
                sys.executable,
                "-m",
                "piptools",
                "compile",
                "--quiet",
                "--allow-unsafe",
                *(("--generate-hashes",) if generate_hashes else ()),
                "--strip-extras",
                "--output-file",
                str(output_path),
                str(requirements_in),
            ),
            extra_env={"PIP_TOOLS_CACHE_DIR": cache_dir},
        )


def _refresh_python_surface_lock(
    repo_root: Path,
    *,
    surface: dependency_management.DependencySurface,
) -> LockHandlerResult:
    """Refresh one declared Python dependency surface."""

    normalized_lock = _normalize_repo_relative_path_token(surface.lock_file)
    lock_path = repo_root / normalized_lock
    if not surface.direct_dependency_files:
        return LockHandlerResult(
            normalized_lock,
            changed=False,
            attempted=False,
            message="Skipped: no direct dependency files are declared.",
        )
    input_display_name = (
        _normalize_repo_relative_path_token(surface.direct_dependency_files[0])
        if len(surface.direct_dependency_files) == 1
        else "configured dependency inputs"
    )
    previous = (
        _split_last_updated(lock_path.read_text().splitlines())
        if lock_path.exists()
        else LockFilePieces([])
    )
    if surface.generate_hashes:
        if not surface.hash_targets:
            raise RuntimeError(
                "Hash-locked dependency surface "
                f"`{surface.surface_id}` requires configured hash_targets."
            )
        compiled = _compile_hash_locked_surface(
            repo_root,
            surface_id=surface.surface_id,
            dependency_files=surface.direct_dependency_files,
            hash_targets=surface.hash_targets,
            source_display_name=input_display_name,
        )
    elif len(surface.direct_dependency_files) == 1 and (
        Path(surface.direct_dependency_files[0]).name == "requirements.in"
    ):
        compiled = _compile_requirements_lock(
            repo_root,
            repo_root / surface.direct_dependency_files[0],
            generate_hashes=False,
            existing_lock_lines=previous.body,
            output_name=Path(normalized_lock).name,
            input_name=input_display_name,
        )
    else:
        compiled = _compile_lock_from_dependency_files(
            repo_root,
            dependency_files=surface.direct_dependency_files,
            output_name=Path(normalized_lock).name,
            generate_hashes=False,
            existing_lock_lines=previous.body,
            input_display_name=input_display_name,
        )
    compiled_cleaned = LockFilePieces(
        _strip_python_lock_option_lines(compiled.body)
    )
    previous_cleaned = LockFilePieces(
        _strip_python_lock_option_lines(previous.body)
    )
    if _normalize_python_lock_semantics_for_mode(
        previous_cleaned.body,
        generate_hashes=surface.generate_hashes,
    ) == _normalize_python_lock_semantics_for_mode(
        compiled_cleaned.body,
        generate_hashes=surface.generate_hashes,
    ):
        if previous_cleaned.body != previous.body:
            lock_path.parent.mkdir(parents=True, exist_ok=True)
            lock_path.write_text(
                "\n".join(compiled_cleaned.body) + "\n",
                encoding="utf-8",
            )
            return LockHandlerResult(
                normalized_lock,
                changed=True,
                attempted=True,
                message=(
                    f"Normalized {normalized_lock} by removing "
                    "environment-specific pip option lines."
                ),
            )
        if previous.body != compiled_cleaned.body:
            lock_path.parent.mkdir(parents=True, exist_ok=True)
            lock_path.write_text(
                "\n".join(compiled_cleaned.body) + "\n",
                encoding="utf-8",
            )
            return LockHandlerResult(
                normalized_lock,
                changed=True,
                attempted=True,
                message=(
                    f"Normalized {normalized_lock} without changing "
                    "resolved pins."
                ),
            )
        return LockHandlerResult(
            normalized_lock,
            changed=False,
            attempted=True,
            message="No content change after pip-compile.",
        )

    lock_path.parent.mkdir(parents=True, exist_ok=True)
    lock_path.write_text("\n".join(compiled.body) + "\n", encoding="utf-8")
    return LockHandlerResult(
        normalized_lock,
        changed=True,
        attempted=True,
        message=f"Updated {normalized_lock}.",
    )


def _refresh_python_requirements_lock(
    repo_root: Path,
    *,
    generate_hashes: bool = False,
) -> LockHandlerResult:
    """Refresh requirements.lock from requirements.in."""
    return _refresh_python_surface_lock(
        repo_root,
        surface=dependency_management.DependencySurface(
            surface_id="requirements-lock",
            enabled=True,
            active=True,
            lock_file="requirements.lock",
            direct_dependency_files=["requirements.in"],
            dependency_files=["requirements.in"],
            dependency_globs=[],
            dependency_dirs=[],
            third_party_file="licenses/THIRD_PARTY_LICENSES.md",
            licenses_dir="licenses",
            report_heading=dependency_management.DEFAULT_REPORT_HEADING,
            manage_licenses_readme=True,
            generate_hashes=generate_hashes,
            required_paths=[],
            hash_targets=[],
        ),
    )


def _compile_lock_from_dependency_files(
    repo_root: Path,
    *,
    dependency_files: Sequence[str],
    output_name: str,
    generate_hashes: bool,
    existing_lock_lines: Sequence[str] | None = None,
    input_display_name: str,
) -> LockFilePieces:
    """Compile one lock from dependency strings declared in manifest files."""

    dependency_lines: List[str] = []
    for raw_path in dependency_files:
        path_token = _normalize_repo_relative_path_token(raw_path)
        if not path_token:
            continue
        manifest_path = repo_root / path_token
        dependency_lines.extend(
            dependency_management._direct_dependency_strings_from_file(
                manifest_path
            )
        )
    if not dependency_lines:
        return LockFilePieces([])

    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_in = Path(tmpdir) / "runtime-requirements.in"
        tmp_in.write_text(
            "\n".join(dependency_lines).rstrip() + "\n",
            encoding="utf-8",
        )
        return _compile_requirements_lock(
            repo_root,
            tmp_in,
            generate_hashes=generate_hashes,
            existing_lock_lines=existing_lock_lines,
            output_name=output_name,
            input_name=input_display_name,
        )


def _surface_dependency_strings(
    repo_root: Path,
    *,
    dependency_files: Sequence[str],
) -> List[str]:
    """Collect dependency strings from one surface's direct inputs."""

    dependency_lines: List[str] = []
    for raw_path in dependency_files:
        path_token = _normalize_repo_relative_path_token(raw_path)
        if not path_token:
            continue
        manifest_path = repo_root / path_token
        dependency_lines.extend(
            dependency_management._direct_dependency_strings_from_file(
                manifest_path
            )
        )
    return dependency_lines


def _run_pip_hash_target_report(
    repo_root: Path,
    *,
    dependency_lines: Sequence[str],
    target: dependency_management.DependencySurfaceTarget,
) -> List[Dict[str, object]]:
    """Resolve one full dependency closure for a configured hash target."""

    if not dependency_lines:
        return []
    with tempfile.TemporaryDirectory() as tmpdir:
        tmp_in = Path(tmpdir) / "hash-target.in"
        tmp_report = Path(tmpdir) / "hash-target-report.json"
        tmp_in.write_text(
            "\n".join(dependency_lines).rstrip() + "\n",
            encoding="utf-8",
        )
        command = [
            sys.executable,
            "-m",
            "pip",
            "install",
            "--dry-run",
            "--ignore-installed",
            "--report",
            str(tmp_report),
            "--only-binary=:all:",
        ]
        for key, value in target.pip.items():
            normalized_key = str(key).strip().replace("_", "-")
            normalized_value = str(value).strip()
            if not normalized_key or not normalized_value:
                continue
            command.extend([f"--{normalized_key}", normalized_value])
        command.extend(["-r", str(tmp_in)])
        env = dict(os.environ)
        env["PIP_DISABLE_PIP_VERSION_CHECK"] = "1"
        # Reviewed tokenized local command execution.
        # Shell use stays forbidden.
        subprocess.run(  # nosec B603
            command,
            cwd=repo_root,
            check=True,
            text=True,
            capture_output=True,
            env=env,
        )
        payload = json.loads(tmp_report.read_text(encoding="utf-8"))
    installs = payload.get("install", [])
    if not isinstance(installs, list):
        raise RuntimeError(
            "pip hash-target report did not contain an install list."
        )
    return installs


def _merge_hash_target_reports(
    *,
    targets: Sequence[dependency_management.DependencySurfaceTarget],
    report_entries: Mapping[str, Sequence[Mapping[str, object]]],
    source_display_name: str,
) -> List[str]:
    """Build one hash-locked requirements body from target reports."""

    grouped: Dict[str, Dict[str, Dict[str, object]]] = {}
    ordered_target_ids = [target.target_id for target in targets]
    target_markers = {target.target_id: target.marker for target in targets}
    all_target_ids = set(ordered_target_ids)
    for target in targets:
        installs = report_entries.get(target.target_id, [])
        for item in installs:
            if not isinstance(item, Mapping):
                continue
            metadata = item.get("metadata", {})
            if not isinstance(metadata, Mapping):
                continue
            name = str(metadata.get("name", "")).strip()
            version = str(metadata.get("version", "")).strip()
            if not name or not version:
                continue
            archive_hashes = (
                item.get("download_info", {})
                .get("archive_info", {})
                .get("hashes", {})
            )
            hashes: set[str] = set()
            if isinstance(archive_hashes, Mapping):
                sha256 = str(archive_hashes.get("sha256", "")).strip()
                if sha256:
                    hashes.add(sha256)
            if not hashes:
                raise RuntimeError(
                    "pip hash-target report did not provide sha256 hashes "
                    f"for `{name}=={version}` in target "
                    f"`{target.target_id}`."
                )
            normalized_name = (
                dependency_management._normalize_distribution_name(name)
            )
            version_map = grouped.setdefault(normalized_name, {})
            entry = version_map.setdefault(
                version,
                {
                    "display_name": name,
                    "hashes": set(),
                    "targets": set(),
                },
            )
            entry["hashes"].update(hashes)
            entry["targets"].add(target.target_id)

    lines: List[str] = [
        "# This file is autogenerated by DevCovenant dependency-management.",
        "",
    ]
    for normalized_name in sorted(grouped):
        versions = grouped[normalized_name]
        for version in sorted(versions):
            entry = versions[version]
            display_name = str(entry["display_name"])
            target_ids = set(entry["targets"])
            requirement_line = f"{display_name}=={version}"
            if target_ids != all_target_ids:
                marker_parts = [
                    f"({target_markers[target_id]})"
                    for target_id in ordered_target_ids
                    if target_id in target_ids
                ]
                requirement_line += " ; " + " or ".join(marker_parts)
            lines.extend(
                _build_hashed_requirement_block(
                    requirement_line,
                    sorted(entry["hashes"]),
                    source_display_name=source_display_name,
                )
            )
            lines.append("")
    if lines and lines[-1] == "":
        lines.pop()
    return lines


def _compile_hash_locked_surface(
    repo_root: Path,
    *,
    surface_id: str,
    dependency_files: Sequence[str],
    hash_targets: Sequence[dependency_management.DependencySurfaceTarget],
    source_display_name: str,
) -> LockFilePieces:
    """Resolve a hash-locked requirements body across configured targets."""

    del surface_id
    dependency_lines = _surface_dependency_strings(
        repo_root,
        dependency_files=dependency_files,
    )
    if not dependency_lines:
        return LockFilePieces([])
    reports: Dict[str, Sequence[Mapping[str, object]]] = {}
    for target in hash_targets:
        reports[target.target_id] = _run_pip_hash_target_report(
            repo_root,
            dependency_lines=dependency_lines,
            target=target,
        )
    return LockFilePieces(
        _merge_hash_target_reports(
            targets=hash_targets,
            report_entries=reports,
            source_display_name=source_display_name,
        )
    )


def _refresh_npm_lock(repo_root: Path) -> LockHandlerResult:
    """Refresh package-lock.json from package.json."""

    package_json = repo_root / "package.json"
    lock_path = repo_root / "package-lock.json"
    if not package_json.exists():
        return LockHandlerResult(
            "package-lock.json",
            changed=False,
            attempted=False,
            message="Skipped: package.json missing.",
        )
    if not _ensure_tool("npm"):
        return LockHandlerResult(
            "package-lock.json",
            changed=False,
            attempted=False,
            message="Skipped: npm not installed.",
        )
    changed = _run_and_detect_change(
        repo_root,
        lock_path,
        ("npm", "install", "--package-lock-only"),
    )
    message = "Updated package-lock.json." if changed else "No change."
    return LockHandlerResult("package-lock.json", changed, True, message)


def _refresh_yarn_lock(repo_root: Path) -> LockHandlerResult:
    """Refresh yarn.lock from package.json."""

    package_json = repo_root / "package.json"
    lock_path = repo_root / "yarn.lock"
    if not package_json.exists():
        return LockHandlerResult(
            "yarn.lock",
            changed=False,
            attempted=False,
            message="Skipped: package.json missing.",
        )
    if not _ensure_tool("yarn"):
        return LockHandlerResult(
            "yarn.lock",
            changed=False,
            attempted=False,
            message="Skipped: yarn not installed.",
        )
    changed = _run_and_detect_change(
        repo_root,
        lock_path,
        ("yarn", "install", "--mode=update-lockfile"),
    )
    message = "Updated yarn.lock." if changed else "No change."
    return LockHandlerResult("yarn.lock", changed, True, message)


def _refresh_pnpm_lock(repo_root: Path) -> LockHandlerResult:
    """Refresh pnpm-lock.yaml from package.json."""

    package_json = repo_root / "package.json"
    lock_path = repo_root / "pnpm-lock.yaml"
    if not package_json.exists():
        return LockHandlerResult(
            "pnpm-lock.yaml",
            changed=False,
            attempted=False,
            message="Skipped: package.json missing.",
        )
    if not _ensure_tool("pnpm"):
        return LockHandlerResult(
            "pnpm-lock.yaml",
            changed=False,
            attempted=False,
            message="Skipped: pnpm not installed.",
        )
    changed = _run_and_detect_change(
        repo_root,
        lock_path,
        ("pnpm", "install", "--lockfile-only"),
    )
    message = "Updated pnpm-lock.yaml." if changed else "No change."
    return LockHandlerResult("pnpm-lock.yaml", changed, True, message)


def _refresh_go_sum(repo_root: Path) -> LockHandlerResult:
    """Refresh go.sum from go.mod."""

    go_mod = repo_root / "go.mod"
    lock_path = repo_root / "go.sum"
    if not go_mod.exists():
        return LockHandlerResult(
            "go.sum",
            changed=False,
            attempted=False,
            message="Skipped: go.mod missing.",
        )
    if not _ensure_tool("go"):
        return LockHandlerResult(
            "go.sum",
            changed=False,
            attempted=False,
            message="Skipped: go not installed.",
        )
    changed = _run_and_detect_change(
        repo_root, lock_path, ("go", "mod", "tidy")
    )
    message = "Updated go.sum." if changed else "No change."
    return LockHandlerResult("go.sum", changed, True, message)


def _refresh_cargo_lock(repo_root: Path) -> LockHandlerResult:
    """Refresh Cargo.lock from Cargo.toml."""

    cargo_toml = repo_root / "Cargo.toml"
    lock_path = repo_root / "Cargo.lock"
    if not cargo_toml.exists():
        return LockHandlerResult(
            "Cargo.lock",
            changed=False,
            attempted=False,
            message="Skipped: Cargo.toml missing.",
        )
    if not _ensure_tool("cargo"):
        return LockHandlerResult(
            "Cargo.lock",
            changed=False,
            attempted=False,
            message="Skipped: cargo not installed.",
        )
    changed = _run_and_detect_change(
        repo_root, lock_path, ("cargo", "generate-lockfile")
    )
    message = "Updated Cargo.lock." if changed else "No change."
    return LockHandlerResult("Cargo.lock", changed, True, message)


def _refresh_composer_lock(repo_root: Path) -> LockHandlerResult:
    """Refresh composer.lock from composer.json."""

    composer_json = repo_root / "composer.json"
    lock_path = repo_root / "composer.lock"
    if not composer_json.exists():
        return LockHandlerResult(
            "composer.lock",
            changed=False,
            attempted=False,
            message="Skipped: composer.json missing.",
        )
    if not _ensure_tool("composer"):
        return LockHandlerResult(
            "composer.lock",
            changed=False,
            attempted=False,
            message="Skipped: composer not installed.",
        )
    changed = _run_and_detect_change(
        repo_root,
        lock_path,
        ("composer", "update", "--lock", "--no-install"),
    )
    message = "Updated composer.lock." if changed else "No change."
    return LockHandlerResult("composer.lock", changed, True, message)


def _refresh_gemfile_lock(repo_root: Path) -> LockHandlerResult:
    """Refresh Gemfile.lock from Gemfile."""

    gemfile = repo_root / "Gemfile"
    lock_path = repo_root / "Gemfile.lock"
    if not gemfile.exists():
        return LockHandlerResult(
            "Gemfile.lock",
            changed=False,
            attempted=False,
            message="Skipped: Gemfile missing.",
        )
    if not _ensure_tool("bundle"):
        return LockHandlerResult(
            "Gemfile.lock",
            changed=False,
            attempted=False,
            message="Skipped: bundler not installed.",
        )
    changed = _run_and_detect_change(repo_root, lock_path, ("bundle", "lock"))
    message = "Updated Gemfile.lock." if changed else "No change."
    return LockHandlerResult("Gemfile.lock", changed, True, message)


def _refresh_pubspec_lock(repo_root: Path) -> LockHandlerResult:
    """Refresh pubspec.lock from pubspec.yaml."""

    pubspec = repo_root / "pubspec.yaml"
    lock_path = repo_root / "pubspec.lock"
    if not pubspec.exists():
        return LockHandlerResult(
            "pubspec.lock",
            changed=False,
            attempted=False,
            message="Skipped: pubspec.yaml missing.",
        )
    if _ensure_tool("flutter"):
        changed = _run_and_detect_change(
            repo_root, lock_path, ("flutter", "pub", "get")
        )
        message = (
            "Updated pubspec.lock via flutter." if changed else "No change."
        )
        return LockHandlerResult("pubspec.lock", changed, True, message)
    if _ensure_tool("dart"):
        changed = _run_and_detect_change(
            repo_root, lock_path, ("dart", "pub", "get")
        )
        message = "Updated pubspec.lock via dart." if changed else "No change."
        return LockHandlerResult("pubspec.lock", changed, True, message)
    return LockHandlerResult(
        "pubspec.lock",
        changed=False,
        attempted=False,
        message="Skipped: neither flutter nor dart is installed.",
    )


def _refresh_podfile_lock(repo_root: Path) -> LockHandlerResult:
    """Refresh Podfile.lock from Podfile."""

    podfile = repo_root / "Podfile"
    lock_path = repo_root / "Podfile.lock"
    if not podfile.exists():
        return LockHandlerResult(
            "Podfile.lock",
            changed=False,
            attempted=False,
            message="Skipped: Podfile missing.",
        )
    if not _ensure_tool("pod"):
        return LockHandlerResult(
            "Podfile.lock",
            changed=False,
            attempted=False,
            message="Skipped: cocoapods is not installed.",
        )
    changed = _run_and_detect_change(
        repo_root,
        lock_path,
        ("pod", "install", "--no-repo-update"),
    )
    message = "Updated Podfile.lock." if changed else "No change."
    return LockHandlerResult("Podfile.lock", changed, True, message)


def _refresh_dotnet_lock(repo_root: Path) -> LockHandlerResult:
    """Refresh packages.lock.json when .NET projects are present."""

    lock_path = repo_root / "packages.lock.json"
    csproj_files = list(repo_root.glob("*.csproj"))
    if not csproj_files:
        return LockHandlerResult(
            "packages.lock.json",
            changed=False,
            attempted=False,
            message="Skipped: no top-level *.csproj file found.",
        )
    if not _ensure_tool("dotnet"):
        return LockHandlerResult(
            "packages.lock.json",
            changed=False,
            attempted=False,
            message="Skipped: dotnet not installed.",
        )
    changed = _run_and_detect_change(
        repo_root,
        lock_path,
        ("dotnet", "restore", "--use-lock-file"),
    )
    message = "Updated packages.lock.json." if changed else "No change."
    return LockHandlerResult("packages.lock.json", changed, True, message)


LOCKFILE_HANDLERS: Dict[str, Callable[[Path], LockHandlerResult]] = {
    "requirements.lock": _refresh_python_requirements_lock,
    "package-lock.json": _refresh_npm_lock,
    "yarn.lock": _refresh_yarn_lock,
    "pnpm-lock.yaml": _refresh_pnpm_lock,
    "go.sum": _refresh_go_sum,
    "Cargo.lock": _refresh_cargo_lock,
    "composer.lock": _refresh_composer_lock,
    "Gemfile.lock": _refresh_gemfile_lock,
    "pubspec.lock": _refresh_pubspec_lock,
    "Podfile.lock": _refresh_podfile_lock,
    "packages.lock.json": _refresh_dotnet_lock,
}


def _descriptor_metadata_lists(
    repo_root: Path,
    policy_id: str,
) -> Tuple[List[str], Dict[str, List[str]]]:
    """Load descriptor defaults into order/list map representation."""

    descriptor = load_policy_descriptor(repo_root, policy_id)
    if descriptor is None:
        raise ValueError(f"Missing policy descriptor for `{policy_id}`.")
    order: List[str] = []
    values: Dict[str, List[str]] = {}
    for key, raw_value in descriptor.metadata.items():
        key_name = str(key).strip()
        if not key_name:
            continue
        order.append(key_name)
        values[key_name] = metadata_value_list(raw_value)
    return order, values


def _resolve_dependency_metadata(repo_root: Path) -> Dict[str, object]:
    """Resolve dependency-management metadata from profiles and config."""

    order, values = _descriptor_metadata_lists(repo_root, POLICY_ID)
    descriptor = load_policy_descriptor(repo_root, POLICY_ID)
    context = build_metadata_context(repo_root)
    location = resolve_script_location(repo_root, POLICY_ID)
    custom_policy = bool(location and location.kind == "custom")
    bundle = resolve_policy_metadata_bundle(
        POLICY_ID,
        order,
        values,
        descriptor,
        context,
        custom_policy=custom_policy,
    )
    surfaces = dependency_management.resolve_dependency_surfaces(
        repo_root=repo_root,
        raw_surfaces=bundle.decode_options().get("surfaces", []),
        include_inactive=True,
    )
    return {"surfaces": surfaces}


def refresh_all(
    repo_root: Path,
    *,
    payload: dict[str, object] | None = None,
) -> dict[str, object]:
    """Refresh selected lockfiles and dependency-management artifacts."""

    metadata = _resolve_dependency_metadata(repo_root)
    surfaces = [
        surface
        for surface in metadata.get("surfaces", [])
        if isinstance(surface, dependency_management.DependencySurface)
        and surface.active
    ]
    results: List[LockHandlerResult] = []
    changed_lockfiles: List[str] = []
    requested_dependency_files: list[str] = []
    if isinstance(payload, dict):
        raw_files = payload.get("changed_dependency_files")
        if isinstance(raw_files, list):
            for entry in raw_files:
                text = str(entry).strip()
                if text:
                    requested_dependency_files.append(text)
    for surface in surfaces:
        lock_name = surface.lock_file
        if not dependency_management.dependency_surface_lock_refresh_requested(
            surface,
            requested_dependency_files,
        ):
            results.append(
                LockHandlerResult(
                    lock_name,
                    changed=False,
                    attempted=False,
                    message="Skipped: no direct lock inputs changed.",
                )
            )
            continue
        result = _refresh_python_surface_lock(
            repo_root,
            surface=surface,
        )
        results.append(result)
        if result.changed:
            changed_lockfiles.append(lock_name)
    changed_dependency_files: List[str] = []
    for dependency_file in requested_dependency_files:
        changed_dependency_files.append(dependency_file)
    for lock_name in changed_lockfiles:
        changed_dependency_files.append(lock_name)
    if not changed_dependency_files:
        changed_dependency_files = list(changed_lockfiles)
    changed_dependency_files = list(
        dict.fromkeys(
            str(entry).strip()
            for entry in changed_dependency_files
            if str(entry).strip()
        )
    )
    modified_license_files: List[Path] = []
    for surface in surfaces:
        if not surface.direct_dependency_files:
            continue
        surface_changed_dependency_files = [
            entry
            for entry in changed_dependency_files
            if dependency_management.dependency_surface_matches(
                surface,
                entry,
            )
        ]
        if not requested_dependency_files:
            surface_changed_dependency_files = sorted(
                dependency_management.dependency_surface_trigger_files(surface)
            )
        modified_license_files.extend(
            dependency_management.refresh_license_artifacts(
                repo_root,
                changed_dependency_files=surface_changed_dependency_files,
                third_party_file=surface.third_party_file,
                licenses_dir=surface.licenses_dir,
                report_heading=surface.report_heading,
                resolved_lock_file=surface.lock_file,
                direct_dependency_files=surface.direct_dependency_files,
                manage_licenses_readme=surface.manage_licenses_readme,
            )
        )
    result_payload = [
        {
            "lock_file": result.lock_file,
            "changed": result.changed,
            "attempted": result.attempted,
            "message": result.message,
        }
        for result in results
    ]
    refreshed_artifacts = [
        path.as_posix() if isinstance(path, Path) else str(path)
        for path in modified_license_files
    ]
    return {
        "message": (
            "Dependency-management refresh completed."
            if results
            else "No metadata-selected lockfiles are configured for this repo."
        ),
        "lock_results": result_payload,
        "refreshed_artifacts": refreshed_artifacts,
    }
